<?php
return [

    [
        'user_id' => 3,
        'title' => 'Appartamento spazioso in centro',
        'slug' => 'appartamento-spazioso',
        'n_rooms' => 3,
        'n_beds' => 4,
        'n_bathrooms' => 2,
        'mq' => 120,
        'address' => 'Largo Ciro Menotti, 18, Pisa',
        'latitude' => 43.7176673,
        'longitude' => 10.4025949,
        'img' => 'image1.jpg',
        'price' => 1500.00,
        'description' => 'Questo è un bellissimo appartamento nel cuore della città.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Appartamento con vista panoramica',
        'slug' => 'appartamento-panoramico',
        'n_rooms' => 2,
        'n_beds' => 2,
        'n_bathrooms' => 1,
        'mq' => 80,
        'address' => 'Via Merulana, 105, Roma',
        'latitude' => 41.8951042,
        'longitude' => 12.5001849,
        'img' => 'image2.jpg',
        'price' => 1200.00,
        'description' => 'Goditi una vista mozzafiato da questo appartamento situato in cima a una collina.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Appartamento moderno vicino al mare',
        'slug' => 'appartamento-moderno',
        'n_rooms' => 2,
        'n_beds' => 3,
        'n_bathrooms' => 2,
        'mq' => 90,
        'address' => 'Via Del Borghetto, 44, Pisa',
        'latitude' => 43.7122008,
        'longitude' => 10.4108351,
        'img' => 'image3.jpg',
        'price' => 1800.00,
        'description' => 'Questo appartamento moderno si trova a pochi passi dalla spiaggia.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Appartamento rustico in campagna',
        'slug' => 'appartamento-rustico',
        'n_rooms' => 4,
        'n_beds' => 6,
        'n_bathrooms' => 3,
        'mq' => 160,
        'address' => 'Via Di Sant\' Erasmo, Roma',
        'latitude' => 41.884436,
        'longitude' => 12.500058,
        'img' => 'image4.jpg',
        'price' => 900.00,
        'description' => 'Questo appartamento rustico offre un ambiente tranquillo e rurale.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Appartamento di lusso in centro',
        'slug' => 'appartamento-lusso',
        'n_rooms' => 4,
        'n_beds' => 5,
        'n_bathrooms' => 4,
        'mq' => 200,
        'address' => 'Via San\' Giovanni in Laterano, 28, Roma',
        'latitude' => 41.888384,
        'longitude' => 12.4998437,
        'img' => 'image5.jpg',
        'price' => 2500.00,
        'description' => 'Questo appartamento di lusso offre servizi premium e una posizione centrale.',
        'visible' => true,
    ],
];