<?php
return [

    [
        'user_id' => 3,
        'title' => 'Alloggio-Host: Pirmin',
        'slug' => 'alloggio-host-pirmin',
        'n_rooms' => 3,
        'n_beds' => 4,
        'n_bathrooms' => 2,
        'mq' => 120,
        'address' => 'Largo Ciro Menotti, 18, Pisa',
        'latitude' => 43.7176673,
        'longitude' => 10.4025949,
        'img' => 'image1.jpg',
        'price' => 1500.00,
        'description' => 'Ti diamo il benvenuto al nostro barile da campeggio numero 3 per un massimo di 3 persone su un meraviglioso altopiano sopra Küssnacht sul Rigi. La vista sul Lago dei Quattro Cantoni, sul Pilatus, fino al Rigi o agli amabili alpaca è meravigliosa. Intorno ci sono altri due barili da campeggio e una tenda LotusBelle bianca. La situazione ha tutto ciò che contraddistingue la Svizzera. Semplicemente natura pura curata nei dettagli. Una permanenza ti rimarrà sicuramente un ricordo meraviglioso.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Intero alloggio: chalet-Host: Manu',
        'slug' => 'intero-alloggio-chalet-host-manu',
        'n_rooms' => 2,
        'n_beds' => 2,
        'n_bathrooms' => 1,
        'mq' => 80,
        'address' => 'Via Merulana, 105, Roma',
        'latitude' => 41.8951042,
        'longitude' => 12.5001849,
        'img' => 'image2.jpg',
        'price' => 1200.00,
        'description' => 'Il nostro chalet si trova nel villaggio di La Crettaz d\'Eison a 1650 m di altitudine. Ci abbiamo vissuto per 5 anni. Oggi è diventato troppo piccolo per noi e abbiamo deciso di metterlo in affitto. Dall\'alloggio sono possibili diverse passeggiate (a piedi o con le racchette da neve, a seconda della stagione), in direzione del villaggio di Eison, della foresta o verso gli alpeggi. Saremo lieti di consigliarvi alcuni itinerari in base alle vostre esigenze.',
        'visible' => true,
    ],
    [
        'user_id' => 2,
        'title' => 'Intero alloggio: casa-Host: Luca',
        'slug' => 'intero-alloggio-casa-host-Luca',
        'n_rooms' => 2,
        'n_beds' => 3,
        'n_bathrooms' => 2,
        'mq' => 90,
        'address' => 'Via Del Borghetto, 44, Pisa',
        'latitude' => 43.7122008,
        'longitude' => 10.4108351,
        'img' => 'image3.jpg',
        'price' => 1800.00,
        'description' => 'Un’oasi di pace, privacy e relax nella natura a pochi minuti dalle spiagge e dai più famosi luoghi della Costa Smeralda. Soffitti in legno con travi a vista, pavimenti in cotto, arredi dalle calde tonalità della terra e viste sulla campagna rendono la Villa Turchese un luogo sereno dove vorrete fermarvi. La piscina panoramica è circondata da un ampio giardino con ulivi e alberi da frutta.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Intero alloggio: chalet-Host: Florence',
        'slug' => 'intero-alloggio-chalet-host-florence',
        'n_rooms' => 4,
        'n_beds' => 6,
        'n_bathrooms' => 3,
        'mq' => 160,
        'address' => 'Via Di Sant\' Erasmo, Roma',
        'latitude' => 41.884436,
        'longitude' => 12.500058,
        'img' => 'image4.jpg',
        'price' => 900.00,
        'description' => 'Questo piccolo chalet accogliente si trova a Les Bois, di fronte al Monte Bianco. A 5 minuti di auto dal centro della città e a 5 minuti a piedi fermate di autobus e treni. Il villaggio è situato in posizione ideale, tra Chamonix e Argentière. Il posto è tranquillo, senza essere lontano da tutto. Le partenze escursionistiche, le piste per lo sci di fondo, il golf, gli impianti di risalita sono facilmente raggiungibili.',
        'visible' => true,
    ],
    [
        'user_id' => 3,
        'title' => 'Agriturismo-Host: Irene',
        'slug' => 'agriturismo-host-irene',
        'n_rooms' => 4,
        'n_beds' => 5,
        'n_bathrooms' => 4,
        'mq' => 20,
        'address' => 'Via San\' Giovanni in Laterano, 28, Roma',
        'latitude' => 41.888384,
        'longitude' => 12.4998437,
        'img' => 'image5.jpg',
        'price' => 2500.00,
        'description' => 'Monolocale di 20 mq con affaccio diretto  alla piscina e giardino, composto da un letto matrimoniale ( oppure 2 letti singoli), un bagno, angolo cottura e patio esterno.  l\'appartamento fa parte dell\' Agriturismo Fulet in cui sono presenti altri 4 appartamenti posti al primo piano dell\'edificio.( vedi foto). Parcheggio privato ed uso wifi gratuito.',
        'visible' => true,
    ],
];